title:             Italia Design Web Toolkit Theme
email:             your-email@example.com
description:       A Jekill Theme derived from Start Bootstrap
author:            Giovanni Gentili
baseurl:           "/"
url:               "http://abc.github.io"

# Social Profiles
twitter_username:  abc
github_username:   abc
facebook_username: abc

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
