title:             Italia Design Web Toolkit Theme
description:       A Jekill Theme derived from Start Bootstrap
author:            Giovanni Gentili
email:             your-email@example.com
baseurl:           "/"
url:               "http://abc.github.io"

# Social Profiles
facebook_username: abc
twitter_username:  abc
youtube_username: abc
github_username: "RegioneUmbria"
repository: RegioneUmbria/adumbria-blog

# Build settings
# permalink: /:categories/:title/
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"#
plugins:
  - jekyll-feed
  - jekyll-paginate

search: true
search_full_content: false

defaults:
# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single
