title:             "Italia Design Web Toolkit Jekyll Theme by G.Gentili 2018"
description:       "A jekyll theme derived from Clean Blog by Start Bootstrap"
email:             your-email@example.com
baseurl:           "/"
url:               "http://abc.github.io"

# Social Profiles
facebook_username: abc
twitter_username:  abc
youtube_username: abc
github_username: "RegioneUmbria"

# Build settings
# permalink: /:categories/:title/
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"#
plugins:
  - jekyll-feed
  - jekyll-paginate

search: true
search_full_content: false

defaults:
# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single
