title:             "Italia Design Web Toolkit Jekyll Theme by G.Gentili 2018"
description:       "A jekyll theme derived from Clean Blog by Start Bootstrap"
baseurl:           "/"
url:               "https://abc.github.io"

# Header data
header_parent_title: Nome ente sovraordinato
header_parent_url: "http://entepubblico.it"
header_language_selector: false
header_logo: assets/images/LogoRegione85x96.svg
header_title: Nome ente o titolo del sito
header_subtitle: sottotitolo
search: true
search_full_content: false
mega_menu: true    # if true, require _data/menu.yml
mega_menu_accedi: false

# Social profiles
social_block: true
social_username: "&commat;AdUmbria"    # short
medium_username: abcuser
facebook_username: abcuser
twitter_username:  abcuser
youtube_username: abcuser
linkedin_username:
github_username: abcuser

# Footer data
footer_logo: assets/images/LogoRegioneWhite.png
footer_title: Nome ente
footer_subtitle: sottotitolo
recapiti1: Recapiti
recapiti2: Via autem reiciendis maiores
recapiti3: autem reiciendis maiores
recapiti4: Tel. (+00) 00.0000.0000
email: your-email@example.it
pec: your-pec@example.it
privacy_url: "http://abc.github.io/privacy"
note_legali_url: "http://abc.github.io/note_legali"
contatti_url: "http://abc.github.io/contatti"

# Build settings
# permalink: /:categories/:title/
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"#
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single
